config/routes.rb
Rails.application.routes.draw do
  resources :hates, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

  get 'account_activations/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'signup'  => 'users#new'

  root 'movies#index'

  resources :movies

  resources :users do
    member do
    get 'user_movies'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:destroy, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  # GET /movies
  def index
    @movies = Movie.all.includes(:user, :likes, :hates).order(sort_column+' desc')
  end

  # GET /movies/1
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  def create
    @movie = Movie.new(movie_params)

    @movie[:user_id] = current_user.id

    if @movie.save
      flash[:info] = 'Movie was successfully created.'
      redirect_to @movie
    else
      render :new
    end
  end

  # PATCH/PUT /movies/1
  def update
    if @movie.update(movie_params)
      flash[:info] = 'Movie was successfully updated.'
      redirect_to @movie
    else
      render :edit
    end
  end

  # DELETE /movies/1
  def destroy
    if @movie.destroy
      flash[:info] = 'Movie was successfully destroyed.'
      redirect_to movies_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :likes, :hates, :user_id)
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find_by_id(@movie.user_id)
      unless (current_user?(@user) || current_user.admin)
        redirect_to(root_url)
      end
    end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control'  %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/movies/_movie.html.erb
<div>
	<br />
<dt>Title: <%= movie.title %></dt>
<dd>Description: <%= movie.description %></dd>
<dd>By user: <%= link_to movie.user.username, user_movies_user_path(movie.user) %></dd>
<dd>Likes: <%= movie.likes_sum %> | Hates: <%= movie.hates_sum %>
<% if logged_in? %>
	<% if current_user.likes_movie?(movie.id) %>
		
			 | You like this movie. 
			<%= link_to 'Unlike', like_url(movie_id:  movie.id, id: current_user.id), method: :delete, class: "btn btn-primary" %>
			or 
			<%= link_to 'Hate', hates_url(:hate => { movie_id:  movie.id, user_id: current_user.id}, status: 'voted' ), method: :post, class: "btn btn-primary" %>
			
	<% elsif current_user.hates_movie?(movie.id) %>
		
			 | You hate this movie. 
			<%= link_to 'Unhate', hate_url(movie_id:  movie.id, id: current_user.id), method: :delete, class: "btn btn-primary" %>
			or 
			<%= link_to 'Like', likes_url(:like => { movie_id:  movie.id, user_id: current_user.id}, status: 'voted' ), method: :post, class: "btn btn-primary" %>
		
	<% elsif current_user.id != movie.user_id %>
			
			 | <%= link_to 'Like', likes_url(:like => { movie_id:  movie.id, user_id: current_user.id}, status: 'none' ), method: :post, class: "btn btn-primary" %>
			<%= link_to 'Hate', hates_url(:hate => { movie_id:  movie.id, user_id: current_user.id}, status: 'none' ), method: :post, class: "btn btn-primary" %>
		</dd>
	<% end %>
	<% store_location %>
<% end %>
</div>

app/views/movies/edit.html.erb
<% provide(:title, 'Editing Movie ' + @movie.title) %>

<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<% provide(:title, 'All Movies') %>
<% if logged_in? %>
<%= link_to 'New Movie', new_movie_path, class: "btn btn-primary" %>
<% end %>
<div>
	<h3>
		Sort by | 
		<%= link_to "Date", :sort => "created_at" %>
		<%= link_to "Likes", :sort => "likes_sum" %>
		<%= link_to "Hates", :sort => "hates_sum" %>
	</h3>
</div>

<%= render @movies %>
<br />

app/views/movies/new.html.erb
<% provide(:title, 'New Movie') %>
<h1>New Movie</h1>

<%= render 'form' %>

app/views/movies/show.html.erb
<% provide(:title, 'Movie ' + @movie.title) %>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @movie.likes_sum %>
</p>

<p>
  <strong>Hates:</strong>
  <%= @movie.hates_sum %>
</p>

<p>
  <strong>User:</strong>
  <%= @movie.user_id %>
</p>