config/routes.rb
Rails.application.routes.draw do
  resources :hates, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

  get 'account_activations/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'signup'  => 'users#new'

  root 'movies#index'

  resources :movies

  resources :users do
    member do
    get 'user_movies'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
<header>

	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">

					<li><%= link_to "Home", root_path %></li>

					<% if logged_in? %>

					<li><%= link_to "My Profile", current_user %></li>
					<li><%= link_to current_user.username, edit_user_path(current_user) %></li>

					<% if current_user.admin?  %>
					<li class="divider"></li>
					<li><%= link_to "some", "#" %></li>
					<% end %>
					<li>
						<%= link_to "Logout", logout_path, method: "delete" %>
					</li>
					
					<% else %>
					<li><%= link_to "Login", login_path %></li>
					<li><%= link_to "SignUp", signup_path %></li>
					<% end %>
				</ul></div>
			</div>
		</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>
      <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>